import os

from telethon.sync import TelegramClient
from telethon.tl.functions.account import UploadWallPaperRequest
from telethon.tl.types import InputFile, WallPaperSettings

from config.api_keys import API_ID, API_HASH

api_id = API_ID
api_hash = API_HASH


async def create_iphone_theme(chat_id, image_path, bg, dark, status_bar, primary_txt, secondary_txt):
    async with TelegramClient('annon', api_id, api_hash) as client:
        # Завантажити зображення на сервери Telegram
        result = await client.upload_file(image_path)

        if result:
            input_file = InputFile(
                id=result.id,
                parts=result.parts,
                name=result.name,
                md5_checksum=result.md5_checksum
            )

            # Створити шпалеру з завантаженого зображення
            wallpaper = await client(UploadWallPaperRequest(
                file=input_file,
                mime_type='image/jpeg',  # тип MIME вашого зображення
                settings=WallPaperSettings()  # налаштування шпалери, якщо потрібно
            ))

            wallpaper_slug = wallpaper.slug
            name = f'{status_bar}_{bg}'
            file_name = f'{bg}{primary_txt}{secondary_txt}.tgios-theme'

            path = os.path.join('ios', 'theme', str(chat_id))
            if not os.path.exists(path):
                os.makedirs(path)

            theme = os.path.join('ios', 'theme', str(chat_id), file_name)

            ios_data = ['',
                        f'name: {name}',
                        'basedOn: day',
                        f'dark: {dark}',
                        'intro:',
                        f'statusBar: {status_bar}',
                        f'primaryText: {primary_txt}',
                        f'accentText: {secondary_txt}',
                        'disabledText: 33999999',
                        f'startButton: {secondary_txt}',
                        'dot: 5e5e5e', 'passcode:',
                        '  bg:',
                        f'    top: {bg}',
                        f'    bottom: {bg}',
                        '  button: clear',
                        'root:',
                        f'  statusBar: {status_bar}',
                        '  tabBar:',
                        f'    background: {bg}',
                        f'    separator: 33{secondary_txt}',
                        f'    icon: a1{secondary_txt}',
                        f'    selectedIcon: {secondary_txt}',
                        f'    text: a1{secondary_txt}',
                        f'    selectedText: {secondary_txt}',
                        f'    badgeBackground: {primary_txt}',
                        f'    badgeStroke: {bg}',
                        f'    badgeText: {bg}', '  navBar:',
                        f'    button: {secondary_txt}',
                        f'    disabledButton: 33{secondary_txt}',
                        f'    primaryText: {primary_txt}',
                        '    secondaryText: 999999',
                        f'    control: {secondary_txt}',
                        f'    accentText: {secondary_txt}',
                        f'    background: {bg}',
                        '    separator: 33000000',
                        f'    badgeFill: {primary_txt}',
                        f'    badgeStroke: {bg}',
                        f'    badgeText: {bg}',
                        '  searchBar:',
                        f'    background: {bg}',
                        f'    accent: {secondary_txt}',
                        f'    inputFill: 33d6d6d6',
                        '    inputText: 000000',
                        f'    inputPlaceholderText: a1{secondary_txt}',
                        '    inputIcon: 33000000',
                        '    inputClearButton: 7b7b81',
                        f'    separator: 33{secondary_txt}',
                        f'  keyboard: {dark}',
                        'list:',
                        f'  blocksBg: {bg}',
                        f'  plainBg: {bg}',
                        f'  primaryText: {primary_txt}',
                        '  secondaryText: 999999',
                        f'  disabledText: 1e{secondary_txt}',
                        f'  accent: {secondary_txt}',
                        f'  highlighted: 1e{secondary_txt}',
                        '  destructive: ff3b30',
                        '  placeholderText: c8c8ce',
                        f'  itemBlocksBg: {bg}',
                        f'  itemHighlightedBg: 1e{secondary_txt}',
                        f'  blocksSeparator: 33{secondary_txt}',
                        f'  plainSeparator: 33{secondary_txt}',
                        '  disclosureArrow: bab9be',
                        '  sectionHeaderText: 6d6d72',
                        '  freeText: 6d6d72',
                        '  freeTextError: cf3030',
                        '  freeTextSuccess: 26972c',
                        '  freeMonoIcon: 7e7e87',
                        '  switch:',
                        '    frame: e0e0e0',
                        '    handle: ffffff',
                        '    content: 77d572',
                        '    positive: 00c900',
                        '    negative: ff3b30',
                        '  disclosureActions:',
                        '    neutral1:',
                        '      bg: 4892f2',
                        '      fg: ffffff',
                        '    neutral2:',
                        '      bg: f09a37',
                        '      fg: ffffff',
                        '    destructive:',
                        '      bg: ff3824',
                        '      fg: ffffff',
                        '    constructive:',
                        '      bg: 00c900',
                        '      fg: ffffff',
                        '    accent:',
                        '      bg: 000000',
                        '      fg: ffffff',
                        '    warning:',
                        '      bg: ff9500',
                        '      fg: ffffff',
                        '    inactive:',
                        '      bg: bcbcc3',
                        '      fg: ffffff',
                        '  check:',
                        '    bg: 000000',
                        '    stroke: c7c7cc',
                        '    fg: ffffff',
                        '  controlSecondary: dedede',
                        '  freeInputField:',
                        f'    bg: {bg}',
                        f'    stroke: {bg}',
                        '    placeholder: 96979d',
                        f'    primary: {primary_txt}',
                        f'    control: {secondary_txt}',
                        '  mediaPlaceholder: e4e4e4',
                        '  scrollIndicator: 4c000000',
                        '  pageIndicatorInactive: e3e3e7',
                        '  inputClearButton: cccccc',
                        'chatList:',
                        f'  bg: {bg}',
                        f'  itemSeparator: 33{secondary_txt}',
                        '  itemBg: 1ed6d6d6',
                        f'  pinnedItemBg: {bg}',
                        f'  itemHighlightedBg: 1e{secondary_txt}',
                        f'  itemSelectedBg: 1e{secondary_txt}',
                        f'  title: {primary_txt}',
                        '  secretTitle: 00b12c',
                        '  dateText: 999999',
                        '  authorName: 999999',
                        '  messageText: 999999',
                        '  messageDraftText: 999999',
                        f'  checkmark: {secondary_txt}',
                        '  pendingIndicator: 999999',
                        '  failedFill: ff3b30',
                        '  failedFg: ffffff',
                        '  muteIcon: 999999',
                        f'  unreadBadgeActiveBg: {secondary_txt}',
                        f'  unreadBadgeActiveText: {bg}',
                        '  unreadBadgeInactiveBg: b6b6bb',
                        '  unreadBadgeInactiveText: ffffff',
                        '  pinnedBadge: 000000',
                        '  pinnedSearchBar: e5e5e5',
                        '  regularSearchBar: e9e9e9',
                        '  sectionHeaderBg: 33d6d6d6',
                        '  sectionHeaderText: 8e8e93',
                        f'  verifiedIconBg: {secondary_txt}',
                        '  verifiedIconFg: ffffff',
                        '  secretIcon: 00b12c',
                        '  pinnedArchiveAvatar:',
                        '    background:',
                        f'      top: 1e{secondary_txt}',
                        f'      bottom: {secondary_txt}',
                        '    foreground: ffffff',
                        '  unpinnedArchiveAvatar:',
                        '    background:',
                        '      top: 1e999999',
                        '      bottom: 999999',
                        '    foreground: ffffff',
                        '  onlineDot: 4cc91f',
                        'chat:',
                        f'  defaultWallpaper: {wallpaper_slug}',
                        '  message:',
                        '    incoming:',
                        '      bubble:',
                        '        withWp:',
                        f'          bg: {bg}',
                        '          highlightedBg: ccdadade',
                        f'          stroke: {bg}',
                        '        withoutWp:',
                        f'          bg: {bg}',
                        '          highlightedBg: ccdadade',
                        f'          stroke: {bg}',
                        f'      primaryText: {primary_txt}',
                        '      secondaryText: 999999',
                        f'      linkText: {secondary_txt}',
                        f'      linkHighlight: 1e{secondary_txt}',
                        '      scam: ff3b30',
                        f'      textHighlight: 1e{secondary_txt}',
                        f'      accentText: {secondary_txt}',
                        f'      accentControl: {secondary_txt}',
                        f'      mediaActiveControl: {secondary_txt}',
                        '      mediaInactiveControl: cacaca',
                        '      pendingActivity: 99525252',
                        f'      fileTitle: {secondary_txt}',
                        '      fileDescription: 999999',
                        '      fileDuration: 99525252',
                        '      mediaPlaceholder: f2f2f2',
                        '      polls:',
                        '        radioButton: c8c7cc',
                        f'        radioProgress: {secondary_txt}',
                        f'        highlight: 1e{secondary_txt}',
                        '        separator: c8c7cc',
                        f'        bar: {secondary_txt}',
                        '      actionButtonsBg:',
                        '        withWp: 66a5a5a5',
                        '        withoutWp: ccffffff',
                        '      actionButtonsStroke:',
                        '        withWp: clear',
                        f'        withoutWp: {secondary_txt}',
                        '      actionButtonsText:',
                        '        withWp: ffffff',
                        f'        withoutWp: {secondary_txt}',
                        f'      textSelection: 4c{secondary_txt}',
                        f'      textSelectionKnob: {secondary_txt}',
                        '    outgoing:',
                        '      bubble:',
                        '        withWp:',
                        '          bg: 696969',
                        '          highlightedBg: ccdadade',
                        '          stroke: 696969',
                        '        withoutWp:',
                        '          bg: 696969',
                        '          highlightedBg: ccdadade',
                        '          stroke: 696969',
                        '      primaryText: ffffff',
                        '      secondaryText: a5ffffff',
                        '      linkText: ffffff',
                        '      linkHighlight: 4cffffff',
                        '      scam: ffffff',
                        '      textHighlight: 4cffffff',
                        '      accentText: ffffff',
                        '      accentControl: ffffff',
                        '      mediaActiveControl: ffffff',
                        '      mediaInactiveControl: a5ffffff',
                        '      pendingActivity: a5ffffff',
                        '      fileTitle: ffffff',
                        '      fileDescription: a5ffffff',
                        '      fileDuration: a5ffffff',
                        '      mediaPlaceholder: 0000f2',
                        '      polls:',
                        '        radioButton: a5ffffff',
                        '        radioProgress: ffffff',
                        '        highlight: 1effffff',
                        '        separator: a5ffffff',
                        '        bar: ffffff',
                        '      actionButtonsBg:',
                        '        withWp: 66a5a5a5',
                        '        withoutWp: ccffffff',
                        '      actionButtonsStroke:',
                        '        withWp: clear',
                        '        withoutWp: 000000',
                        '      actionButtonsText:',
                        '        withWp: ffffff',
                        f'        withoutWp: {secondary_txt}',
                        '      textSelection: 33ffffff',
                        '      textSelectionKnob: ffffff',
                        '    freeform:',
                        '      withWp:',
                        '        bg: e5e5ea',
                        '        highlightedBg: dadade',
                        '        stroke: e5e5ea',
                        '      withoutWp:',
                        '        bg: e5e5ea',
                        '        highlightedBg: dadade',
                        '        stroke: e5e5ea',
                        '    infoPrimaryText: 000000',
                        '    infoLinkText: 004bad',
                        '    outgoingCheck: ffffff',
                        '    mediaDateAndStatusBg: 7f000000',
                        '    mediaDateAndStatusText: ffffff',
                        '    shareButtonBg:',
                        '      withWp: 66a5a5a5',
                        '      withoutWp: ccffffff',
                        '    shareButtonStroke:',
                        '      withWp: clear',
                        '      withoutWp: e5e5ea',
                        '    shareButtonFg:',
                        '      withWp: ffffff',
                        f'      withoutWp: {secondary_txt}',
                        '    mediaOverlayControl:',
                        '      bg: 99000000',
                        '      fg: ffffff',
                        '    selectionControl:',
                        f'      bg: {secondary_txt}',
                        '      stroke: c7c7cc',
                        '      fg: ffffff',
                        '    deliveryFailed:',
                        '      bg: ff3b30',
                        '      fg: ffffff',
                        '    mediaHighlightOverlay: 99ffffff',
                        '  serviceMessage:',
                        '    components:',
                        '      withDefaultWp:',
                        '        bg: ccffffff',
                        '        primaryText: 8d8e93',
                        '        linkHighlight: 3f748391',
                        '        scam: ff3b30',
                        '        dateFillStatic: ccffffff',
                        '        dateFillFloat: ccffffff',
                        '      withCustomWp:',
                        '        bg: 66a5a5a5',
                        '        primaryText: ffffff',
                        '        linkHighlight: 3f748391',
                        '        scam: ff3b30',
                        '        dateFillStatic: 66a5a5a5',
                        '        dateFillFloat: 44a5a5a5',
                        '    unreadBarBg: ffffff',
                        '    unreadBarStroke: ffffff',
                        '    unreadBarText: 8d8e93',
                        '    dateText:',
                        '      withWp: ffffff',
                        '      withoutWp: 8d8e93',
                        '  inputPanel:',
                        f'    panelBg: {bg}',
                        f'    panelSeparator: 33{secondary_txt}',
                        f'    panelControlAccent: {secondary_txt}',
                        '    panelControl: 999999',
                        '    panelControlDisabled: 1e999999',
                        '    panelControlDestructive: ff3b30',
                        '    inputBg: 1ed6d6d6',
                        f'    inputStroke: {bg}',
                        '    inputPlaceholder: 33999999',
                        f'    inputText: {primary_txt}',
                        f'    inputControl: {secondary_txt}',
                        f'    actionControlBg: {secondary_txt}',
                        '    actionControlFg: ffffff',
                        f'    primaryText: {primary_txt}',
                        '    secondaryText: 999999',
                        f'    mediaRecordDot: {secondary_txt}',
                        '    mediaRecordControl:',
                        f'      button: {secondary_txt}',
                        f'      micLevel: 1e{secondary_txt}',
                        '      activeIcon: ffffff',
                        '  inputMediaPanel:',
                        '    panelSeparator: bec2c6',
                        '    panelIcon: 858e99',
                        '    panelHighlightedIconBg: 33858e99',
                        '    stickersBg: e8ebf0',
                        '    stickersSectionText: 9099a2',
                        '    stickersSearchBg: d9dbe1',
                        '    stickersSearchPlaceholder: 8e8e93',
                        '    stickersSearchPrimary: 000000',
                        '    stickersSearchControl: 8e8e93',
                        '    gifsBg: ffffff',
                        '  inputButtonPanel:',
                        '    panelBg: dee2e6',
                        '    panelSeparator: bec2c6',
                        '    buttonBg: ffffff',
                        '    buttonStroke: c3c7c9',
                        '    buttonHighlightedBg: a8b3c0',
                        '    buttonHighlightedStroke: c3c7c9',
                        '    buttonText: 000000',
                        '  historyNav:',
                        f'    bg: {bg}',
                        f'    stroke: {bg}',
                        f'    fg: {primary_txt}',
                        f'    badgeBg: {secondary_txt}',
                        f'    badgeStroke: {secondary_txt}',
                        '    badgeText: ffffff',
                        'actionSheet:',
                        '  dim: 66000000',
                        '  bgType: light',
                        '  opaqueItemBg: ffffff',
                        '  itemBg: ddffffff',
                        '  opaqueItemHighlightedBg: e5e5e5',
                        '  itemHighlightedBg: b2e5e5e5',
                        '  opaqueItemSeparator: e5e5e5',
                        f'  standardActionText: {secondary_txt}',
                        '  destructiveActionText: ff3b30',
                        '  disabledActionText: b3b3b3',
                        '  primaryText: 000000',
                        '  secondaryText: 5e5e5e',
                        f'  controlAccent: {secondary_txt}',
                        '  inputBg: e9e9e9',
                        '  inputHollowBg: ffffff',
                        '  inputBorder: e4e4e6',
                        '  inputPlaceholder: 818086',
                        '  inputText: 000000',
                        '  inputClearButton: 7b7b81',
                        '  checkContent: ffffff',
                        'contextMenu:',
                        '  dim: 33000a26',
                        '  background: c6f9f9f9',
                        '  itemSeparator: 333c3c43',
                        '  sectionSeparator: 338a8a8a',
                        '  itemBg: 00000000',
                        '  itemHighlightedBg: 333c3c43',
                        '  primary: 000000',
                        '  secondary: cc000000',
                        '  destructive: ff3b30',
                        'notification:',
                        '  bg: ffffff',
                        '  primaryText: 000000',
                        '  expanded:',
                        '    bgType: light',
                        '    navBar:',
                        '      background: ffffff',
                        '      primaryText: 000000',
                        '      control: 7e8791',
                        '      separator: b1b1b1']

            with open(theme, 'w') as f:
                for row in ios_data:
                    f.write(str(row) + '\n')

    return theme
